# Provider Page
twitter_page: "https://twitter.com/"
facebook_page: "https://www.facebook.com/"
github_page: "https://github.com/"

# アプリケーション名
app_name: "ThreeStars"

# プログラマTwitterID
programmer_twitter_id: "shu_0115"

# デザイナーTwitterID
designer_twitter_id: "DESIGNER_TWITTER_ID"

# 曜日
weekday: ["日", "月", "火", "水", "木", "金", "土"]

# 評価
star:
  1: '良い'
  2: 'とても良い'
  3: 'めちゃくちゃ良い'

# アマゾンアフィリエイトID
amazon_affiliate_id: 'shu0115-22'

# メール送信者
mailer_sender: "rails.dev0115@gmail.com"
